[package]
name = "rusty-vm-2"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.2"
colored = "3.0.0"
derive_more = { version = "2.1.0", features = ["full"] }
macroquad = "0.4.14"
num_enum = "0.7.5"
